### PR TITLE
Week1-MLOps

### PR DESCRIPTION
**Pull request by somtirtha205**
Simple Data Processing done on the Hotel Reservation dataset in VSCode. Feature engineering and model creation have not been implemented yet. Packaging of code was done using uv in VSCode.

## Release Notes

- **New Features**
	- Introduced a new configuration file for Databricks integration.
	- Added data processing scripts for hotel reservation data, including loading, preprocessing, and modeling pipelines.
	- Implemented a `DataProcessor` class for streamlined data handling.
	- Added a new configuration file defining parameters for the hotel reservation project.
	- Introduced a new data processing pipeline for hotel reservation data using Pandas and Scikit-learn.

- **Bug Fixes**
	- Updated CI workflow for better dependency management and pre-commit checks.

- **Documentation**
	- Revised `README.md` for improved clarity and formatting.

- **Chores**
	- Updated project metadata in `pyproject.toml` to reflect rebranding.
	- Added `.databricks` to `.gitignore` to exclude specific files from version control.

### CODE REVIEW

**Comment by basakeskili** [comment]
pre-commit hooks fail in the ci.yml.

You can see in the actions run, what needs to be fixed: https://github.com/end-to-end-mlops-databricks/marvelous-databricks-course-somtirtha205/actions/runs/11466784597/job/31908240283

You can apply the changes suggested and see if ci.yml succeeds. If you need help, let me know!

**Comment by somtirtha205** [comment]
pre-commit checks are finally successful

**Comment by basakeskili** [comment]
Looks good! You can also try creating .whl file for your custom package and install in your environment as a practice.

**Comment by basakeskili** [comment]
Looks good!

Have you also tried creating .whl file for your package?

**Review by basakeskili — APPROVED** [review]

**Pull request merged**
